apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-crud-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-k8s-mysql
  template:
    metadata:
      labels:
        app: springboot-k8s-mysql
    spec:
      containers:
        - name: springboot-k8s-mysql
          image: azaruddinmohd12/product_kube:1.0.0
          ports:
            - containerPort: 8088
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: product_demo_kube
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: root
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8088
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8088
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s-mysql
spec:
  selector:
    app: springboot-k8s-mysql
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_DATABASE
              value: "product_demo_kube"
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP
