#persistence volumn
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mysql-pv-claim
    labels:
        app: mysql
        tier: database
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
---
#mysql deployment
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql
    labels:
        app: mysql
        tier: database
spec:
    selector:
        matchLabels:
            app: mysql
            tier: database
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: mysql
                tier: database
        spec:
            containers:
                - image: mysql:8.0.27
                  name: mysql
                  env:
                      - name: MYSQL_ROOT_PASSWORD
                        value: root
                      - name: MYSQL_DATABASE
                        value: product_demo_kube-2
                  ports:
                      - containerPort: 3306
                        name: mysql
                  volumeMounts:
                      - name: mysql-persistent-storage
                        mountPath: /var/lib/mysql
            volumes:
                - name: mysql-persistent-storage
                  persistentVolumeClaim:
                      claimName: mysql-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
    tier: database
#  type: ClusterIP  # Use LoadBalancer if needed
  clusterIP: None
